### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/plugin-AnonymousPiwikUsageMeasurement#73]
Hi guys,
Honestly, I am not sure what this plugin is doing.
At the beginning I thought it was sending data to the Matomo team, but by reading the description I am not even sure that it is doing it.

**Comment by justinvelluppillai** [comment]
Hi @Chardonneaur is the description of this plugin here insufficient? https://plugins.matomo.org/AnonymousPiwikUsageMeasurement

It would be good if you could clarify what you are wanting with this issue. If it's updates to docs then linking the specific doc where you expect to find the information would be helpful.

**Comment by Chardonneaur** [comment]
thank you for your response @justinvelluppillai well, if with your own words, you could tell me what this plugin is in fact doing, I will probably be able to be more explicit.
But so far, when I read its description I cannot even say what it is doing? Is it sending data to InnoCraft? is it sending data to a third party player? I have no idea when I read and install the plugin.

**Comment by AltamashShaikh** [comment]
@Chardonneaur So you can configure the plugin to send the usage info to your own Matomo Instance or to a different instance.
![Screenshot from 2022-07-25 13-46-00](https://user-images.githubusercontent.com/14902277/180730916-eca6d8df-254e-47d2-801e-39ffbcfa858b.png)

So if you configure siteID in the above setting it will send the usage info to that site and similarly if you configure an customMatomo URL it will send the info to that customMatomo too

To know what data is tracked you can refer this link - https://github.com/matomo-org/plugin-AnonymousPiwikUsageMeasurement/blob/4.x-dev/README.md

**Comment by Chardonneaur** [comment]
Thank you so much, now I am getting it.
Here was my confusion, this is not a plugin to send data to the Innocraft team in order to know how Matomo end users are using Matomo.
This is not a plugin in order to send the data of a given website in order to feed a potential report to make benchmarking (for example how ecommerce websites are using Matomo).
This is a plugin, mostly for sys admin, in order to know how people within the same organization, which are using Matomo are using Matomo. So it is like the activity log premium feature.
